apiVersion: apps/v1
kind: Deployment
metadata:
  name: kodecamp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kodecamp-app
  template:
    metadata:
      labels:
        app: kodecamp-app
    spec:
      containers:
        - name: kodecamp-app
          image: oma16/githubusersearch-app:v1
          ports:
            - containerPort: 8000
          