---
apiVersion: v1
kind: Service
metadata:
  name: kodecamp-service
spec:
  type: NodePort
  selector:
    app: kodecamp-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30007