name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t oma16/githubusersearch-app:v1 .
        docker push oma16/githubusersearch-app:v1

  
    - name: Set up SSH
      uses: actions/ssh-agent@v2
      with:
        key: ${{ secrets.EC2_SSH_KEY }}

    - name: Connect to EC2 instance
      run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_PUBLIC_IP }}

    - name: Configure kubectl
      run: |
        export MINIKUBE_IP=$(minikube ip)
        eval $(minikube docker-env)
        kubectl config set-cluster minikube --server=https://${MINIKUBE_IP}:8443 --certificate-authority=/var/lib/minikube/ca.crt
        kubectl config set-credentials minikube --client-certificate=/var/lib/minikube/client.crt --client-key=/var/lib/minikube/client.key
        kubectl config set-context minikube --cluster=minikube --user=minikube
        kubectl config use-context minikube   


    - name: Deploy application
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
      
