name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t oma16/githubusersearch-app:v1 .
        docker push oma16/githubusersearch-app:v1

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: SSH to EC2 and deploy to Minikube
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
    - name: Configure kubectl
      run: |
        export MINIKUBE_IP=$(minikube ip)
        eval $(minikube docker-env)
        kubectl config set-cluster minikube --server=https://${MINIKUBE_IP}:8443 --certificate-authority=/var/lib/minikube/ca.crt
        kubectl config set-credentials minikube --client-certificate=/var/lib/minikube/client.crt --client-key=/var/lib/minikube/client.key
        kubectl config set-context minikube --cluster=minikube --user=minikube
        kubectl config use-context minikube   
        script: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
    - name: Verify Deployment
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          kubectl get pods
      
